var model = {
    squaresModel: [],
    piecesModel: [],
    possibleMoves: [],

    getSquaresModel: function () {
        //return [
        //    { 'id': '81', 'color': 'white', 'piece': 'BQR' },
        //    { 'id': '82', 'color': 'black', 'piece': 'BQN' },
        //    { 'id': '83', 'color': 'white', 'piece': 'BQB' },
        //    { 'id': '84', 'color': 'black', 'piece': 'BQ1' },
        //    { 'id': '85', 'color': 'white', 'piece': 'BK' },
        //    { 'id': '86', 'color': 'black', 'piece': 'BKB' },
        //    { 'id': '87', 'color': 'white', 'piece': 'BKN' },
        //    { 'id': '88', 'color': 'black', 'piece': 'BKR' },

        //    { 'id': '71', 'color': 'black', 'piece': 'BP1' },
        //    { 'id': '72', 'color': 'white', 'piece': 'BP2' },
        //    { 'id': '73', 'color': 'black', 'piece': 'BP3' },
        //    { 'id': '74', 'color': 'white', 'piece': 'BP4' },
        //    { 'id': '75', 'color': 'black', 'piece': 'BP5' },
        //    { 'id': '76', 'color': 'white', 'piece': 'BP6' },
        //    { 'id': '77', 'color': 'black', 'piece': 'BP7' },
        //    { 'id': '78', 'color': 'white', 'piece': 'BP8' },

        //    { 'id': '61', 'color': 'white', 'piece': '' },
        //    { 'id': '62', 'color': 'black', 'piece': '' },
        //    { 'id': '63', 'color': 'white', 'piece': '' },
        //    { 'id': '64', 'color': 'black', 'piece': '' },
        //    { 'id': '65', 'color': 'white', 'piece': '' },
        //    { 'id': '66', 'color': 'black', 'piece': '' },
        //    { 'id': '67', 'color': 'white', 'piece': '' },
        //    { 'id': '68', 'color': 'black', 'piece': '' },

        //    { 'id': '51', 'color': 'black', 'piece': '' },
        //    { 'id': '52', 'color': 'white', 'piece': '' },
        //    { 'id': '53', 'color': 'black', 'piece': '' },
        //    { 'id': '54', 'color': 'white', 'piece': '' },
        //    { 'id': '55', 'color': 'black', 'piece': '' },
        //    { 'id': '56', 'color': 'white', 'piece': '' },
        //    { 'id': '57', 'color': 'black', 'piece': '' },
        //    { 'id': '58', 'color': 'white', 'piece': '' },

        //    { 'id': '41', 'color': 'white', 'piece': '' },
        //    { 'id': '42', 'color': 'black', 'piece': '' },
        //    { 'id': '43', 'color': 'white', 'piece': '' },
        //    { 'id': '44', 'color': 'black', 'piece': '' },
        //    { 'id': '45', 'color': 'white', 'piece': '' },
        //    { 'id': '46', 'color': 'black', 'piece': '' },
        //    { 'id': '47', 'color': 'white', 'piece': '' },
        //    { 'id': '48', 'color': 'black', 'piece': '' },

        //    { 'id': '31', 'color': 'black', 'piece': '' },
        //    { 'id': '32', 'color': 'white', 'piece': '' },
        //    { 'id': '33', 'color': 'black', 'piece': '' },
        //    { 'id': '34', 'color': 'white', 'piece': '' },
        //    { 'id': '35', 'color': 'black', 'piece': '' },
        //    { 'id': '36', 'color': 'white', 'piece': '' },
        //    { 'id': '37', 'color': 'black', 'piece': '' },
        //    { 'id': '38', 'color': 'white', 'piece': '' },

        //    { 'id': '21', 'color': 'white', 'piece': 'WP1' },
        //    { 'id': '22', 'color': 'black', 'piece': 'WP2' },
        //    { 'id': '23', 'color': 'white', 'piece': 'WP3' },
        //    { 'id': '24', 'color': 'black', 'piece': 'WP4' },
        //    { 'id': '25', 'color': 'white', 'piece': 'WP5' },
        //    { 'id': '26', 'color': 'black', 'piece': 'WP6' },
        //    { 'id': '27', 'color': 'white', 'piece': 'WP7' },
        //    { 'id': '28', 'color': 'black', 'piece': 'WP8' },

        //    { 'id': '11', 'color': 'black', 'piece': 'WQR' },
        //    { 'id': '12', 'color': 'white', 'piece': 'WQN' },
        //    { 'id': '13', 'color': 'black', 'piece': 'WQB' },
        //    { 'id': '14', 'color': 'white', 'piece': 'WQ1' },
        //    { 'id': '15', 'color': 'black', 'piece': 'WK' },
        //    { 'id': '16', 'color': 'white', 'piece': 'WKB' },
        //    { 'id': '17', 'color': 'black', 'piece': 'WKN' },
        //    { 'id': '18', 'color': 'white', 'piece': 'WKR' }
        //];

        return [
            { 'id': '81', 'color': 'white', 'piece': 'BQR' },
            { 'id': '82', 'color': 'black', 'piece': 'BQN' },
            { 'id': '83', 'color': 'white', 'piece': 'BQB' },
            { 'id': '84', 'color': 'black', 'piece': '' },
            { 'id': '85', 'color': 'white', 'piece': 'BK' },
            { 'id': '86', 'color': 'black', 'piece': 'BKB' },
            { 'id': '87', 'color': 'white', 'piece': 'BKN' },
            { 'id': '88', 'color': 'black', 'piece': 'BKR' },

            { 'id': '71', 'color': 'black', 'piece': 'BP1' },
            { 'id': '72', 'color': 'white', 'piece': 'BP2' },
            { 'id': '73', 'color': 'black', 'piece': 'BP3' },
            { 'id': '74', 'color': 'white', 'piece': 'BP4' },
            { 'id': '75', 'color': 'black', 'piece': 'BP5' },
            { 'id': '76', 'color': 'white', 'piece': 'BP6' },
            { 'id': '77', 'color': 'black', 'piece': 'BP7' },
            { 'id': '78', 'color': 'white', 'piece': 'BP8' },

            { 'id': '61', 'color': 'white', 'piece': '' },
            { 'id': '62', 'color': 'black', 'piece': '' },
            { 'id': '63', 'color': 'white', 'piece': '' },
            { 'id': '64', 'color': 'black', 'piece': '' },
            { 'id': '65', 'color': 'white', 'piece': '' },
            { 'id': '66', 'color': 'black', 'piece': '' },
            { 'id': '67', 'color': 'white', 'piece': '' },
            { 'id': '68', 'color': 'black', 'piece': '' },

            { 'id': '51', 'color': 'black', 'piece': '' },
            { 'id': '52', 'color': 'white', 'piece': 'WQN' },
            { 'id': '53', 'color': 'black', 'piece': '' },
            { 'id': '54', 'color': 'white', 'piece': '' },
            { 'id': '55', 'color': 'black', 'piece': '' },
            { 'id': '56', 'color': 'white', 'piece': '' },
            { 'id': '57', 'color': 'black', 'piece': '' },
            { 'id': '58', 'color': 'white', 'piece': '' },

            { 'id': '41', 'color': 'white', 'piece': '' },
            { 'id': '42', 'color': 'black', 'piece': '' },
            { 'id': '43', 'color': 'white', 'piece': '' },
            { 'id': '44', 'color': 'black', 'piece': '' },
            { 'id': '45', 'color': 'white', 'piece': '' },
            { 'id': '46', 'color': 'black', 'piece': 'BQ1' },
            { 'id': '47', 'color': 'white', 'piece': '' },
            { 'id': '48', 'color': 'black', 'piece': '' },

            { 'id': '31', 'color': 'black', 'piece': '' },
            { 'id': '32', 'color': 'white', 'piece': '' },
            { 'id': '33', 'color': 'black', 'piece': '' },
            { 'id': '34', 'color': 'white', 'piece': '' },
            { 'id': '35', 'color': 'black', 'piece': '' },
            { 'id': '36', 'color': 'white', 'piece': 'WK' },
            { 'id': '37', 'color': 'black', 'piece': '' },
            { 'id': '38', 'color': 'white', 'piece': '' },

            { 'id': '21', 'color': 'white', 'piece': 'WP1' },
            { 'id': '22', 'color': 'black', 'piece': 'WP2' },
            { 'id': '23', 'color': 'white', 'piece': 'WP3' },
            { 'id': '24', 'color': 'black', 'piece': 'WP4' },
            { 'id': '25', 'color': 'white', 'piece': 'WP5' },
            { 'id': '26', 'color': 'black', 'piece': 'WP6' },
            { 'id': '27', 'color': 'white', 'piece': 'WP7' },
            { 'id': '28', 'color': 'black', 'piece': 'WP8' },

            { 'id': '11', 'color': 'black', 'piece': 'WQR' },
            { 'id': '12', 'color': 'white', 'piece': '' },
            { 'id': '13', 'color': 'black', 'piece': 'WQB' },
            { 'id': '14', 'color': 'white', 'piece': 'WQ1' },
            { 'id': '15', 'color': 'black', 'piece': '' },
            { 'id': '16', 'color': 'white', 'piece': 'WKB' },
            { 'id': '17', 'color': 'black', 'piece': 'WKN' },
            { 'id': '18', 'color': 'white', 'piece': 'WKR' }
        ];
    },

    getPiecesModel: function () {
        return [
            { 'id': 'WQR', 'pieceType': 'R', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WQN', 'pieceType': 'N', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WQB', 'pieceType': 'B', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WQ1', 'pieceType': 'Q', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WK', 'pieceType': 'K', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WKB', 'pieceType': 'B', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WKN', 'pieceType': 'N', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WKR', 'pieceType': 'R', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP1', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP2', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP3', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP4', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP5', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP6', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP7', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },
            { 'id': 'WP8', 'pieceType': 'P', 'color': 'white', 'hasMoved': false, 'enPassant': false },

            { 'id': 'BQR', 'pieceType': 'R', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BQN', 'pieceType': 'N', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BQB', 'pieceType': 'B', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BQ1', 'pieceType': 'Q', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BK', 'pieceType': 'K', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BKB', 'pieceType': 'B', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BKN', 'pieceType': 'N', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BKR', 'pieceType': 'R', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP1', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP2', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP3', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP4', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP5', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP6', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP7', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false },
            { 'id': 'BP8', 'pieceType': 'P', 'color': 'black', 'hasMoved': false, 'enPassant': false }
        ];
    }
}
